#!/bin/sh

GLASPOT="/opt/glaspot/trunk"
PID_FILE="/var/run/glaspot.pid"

do_start () {

	if [ -f $PID_FILE ]
	then
		echo "pidfile $PID_FILE already exists."
	else
		cd $GLASPOT
		echo "Starting..."
		python webserver.py > run_log &
		echo $! > /var/run/glaspot.pid
	fi

}
do_stop () {
	
	if [ -f $PID_FILE ]
	then
		echo "Stopping..."
		kill $(cat $PID_FILE)
		rm $PID_FILE
	else
		echo "No pidfile. If you sure glaspot is running kill it manually"
	fi

}
case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;

  restart)
	do_start
	do_stop
	;;
  *)
	echo "Usage: /etc/init.d/glaspot {start|stop|restart}"
	exit 1
esac

exit 0
